name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: # This will enable the on-demand action


jobs:
  build:
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - uses: mymindstorm/setup-emsdk@v11
    - name: 'yarn cache'
      uses: actions/cache@v2
      with:
        path: |
          ~/.yarn
          ~/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build  
    - name: Test
      run: yarn test
    - name: Bench
      run: yarn test bench