name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch: # This will enable the on-demand action


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    steps:
    - uses: actions/checkout@v3
    - name: Setup node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: 'emcc cache'
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    - name: 'yarn cache'
      uses: actions/cache@v2
      with:
        path: |
          ~/.yarn
          ~/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn install
    - name: Test
      run: yarn test
    - name: Bench
      run: yarn test bench
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: 'emcc cache'
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    - name: 'yarn cache'
      uses: actions/cache@v2
      with:
        path: |
          ~/.yarn
          ~/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Bench
      run: yarn test bench
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: 'emcc cache'
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    - name: 'yarn cache'
      uses: actions/cache@v2
      with:
        path: |
          ~/.yarn
          ~/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn install
    - name: Test
      run: yarn test
    - name: Bench
      run: yarn test bench
